### PR TITLE
add aws cli from centos7-java7 for some job process

### PR DESCRIPTION
**Pull request by wjia7**
using same code as centos7-java7 to add aws cli to dockerfile

### CODE REVIEW

**Review by miketypeguy — COMMENTED** [review]
Did you check to see that it builds in dockerhub correctly?

**Comment by haggaret** [comment]
> Did you check to see that it builds in dockerhub correctly?

Mike is right - looks like it's failing to build on DockerHub

**Comment by wjia7** [comment]
Yes, I am looking into it right now. looks like ruby module might be outdated. It's taking a bit longer than expected to find the correct version

**Comment by wjia7** [comment]
build locally and ready for merge

**Review by haggaret — APPROVED** [review]

**Pull request merged**
